CREATE TABLE PESSOA (
   ID INT PRIMARY KEY IDENTITY,
   NOME VARCHAR(255),
   USUARIO VARCHAR(50),
   EMAIL VARCHAR(255),
   TELEFONE VARCHAR(20),
   CEP VARCHAR(26),
   ENDERECO VARCHAR(255),
   CIDADE VARCHAR(50),
   PAIS VARCHAR(50),
   DATA_NASCIMENTO DATE,
   CARGO_ID INT
);

CREATE TABLE PESSOA_SALARIO(
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	PESSOA_ID INT NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA(ID) 
);

CREATE TABLE CARGO(
ID INT PRIMARY KEY IDENTITY NOT NULL,
NOME VARCHAR(255),
SALARIO DECIMAL(10,2) NOT NULL,
);
--IMPORTANDO DADOS 
INSERT INTO PESSOA (NOME,USUARIO,EMAIL,TELEFONE,CEP,ENDERECO,CIDADE,PAIS,DATA_NASCIMENTO,CARGO_ID) 
SELECT NOME,USUARIO,EMAIL,TELEFONE,CEP,ENDERECO,CIDADE,PAIS,DATA_NASCIMENTO,CARGO_ID
FROM  PESSOA_OLD;


--IMPORTAR DADOS DAS TABELAS EXISTENTE 
INSERT INTO PESSOA_SALARIO(PESSOA_ID,SALARIO) 
SELECT P.ID, C.SALARIO
FROM  PESSOA P 
INNER JOIN CARGO C ON P.CARGO_ID = C.ID

SELECT * FROM PESSOA_SALARIO ORDER BY ID DESC

--RESETAR ID DAS TABELAS
DBCC CHECKIDENT ('PESSOA_SALARIO', RESEED, 0);
DELETE FROM PESSOA_SALARIO 

DELETE FROM PESSOA_SALARIO WHERE ID = 3000
SELECT * FROM PESSOA_SALARIO ORDER BY ID ASC

-- TRAZER DADOS DA PESSOA COM O NOME DO CARGO
SELECT P.ID AS ID, P.NOME AS NOME, P.USUARIO AS USUÁRIO, P.EMAIL AS 'E-MAIL', P.TELEFONE AS TELEFONE, P.CEP AS CEP, P.ENDERECO AS ENDEREÇO, P.CIDADE AS CIDADE, P.PAIS AS PAÍS, P.DATA_NASCIMENTO AS 'DATA DE NASCIMENTO', C.NOME AS CARGO FROM PESSOA P 
INNER JOIN CARGO C ON P.CARGO_ID = C.ID

-- TRAZER DADOS PESSOA COM CARGO E SALARIO
SELECT PS.ID AS IDPESSOASALARIO, P.NOME AS NOME, PS.SALARIO AS SALÁRIO, C.NOME AS 'NOME DO CARGO' 
FROM PESSOA_SALARIO PS
INNER JOIN PESSOA P ON P.ID = PS.PESSOA_ID
INNER JOIN CARGO C ON C.ID = P.CARGO_ID


